name: Tester

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  checkPygame:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - run: python -m pip install --upgrade pip; python3 -m pip install pygame
  speedTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test.py
        run: python test.py
