name: Tester

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  speedTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test.py
        run: python test.py
